### ISSUE TITLE
pipe symbol attached to tokens and other issues with punctuation

### ISSUE THREAD

**Issue by wanthalf** [textlab/mtag#1]
When tagging the following non-Norwegian fragment (usually inside an otherwise Norwegian text, of course, but it also replicates when isolated), we get pipe symbols (not present in the source text) attached to tokens and punctuation symbols (present in the text) attached to them as well:

```
«… Fräulein von Kulp


may turn, her hand upon the door;

```

The output is:

```
"<«>"
	"$«" <anf>
"<…>"
	"…" subst prop
"<fräulein>"
	"Fräulein" subst prop <*>
"<von>"
	"von" prep
	"von" subst appell fem ub ent
	"von" subst appell mask ub ent
	"vone" verb imp
"<kulp|>"
	"Kulp|" subst prop <*>
"<may>"
	"may" ukjent
"<turn>"
	"turn" subst appell mask ubøy
	"turne" verb imp
"<,>"
	"$," <komma>
	"$," clb <komma>
"<her>"
	"her" adv
	"her" prep
"<hand>"
	"hand" subst appell fem ub ent
	"hand" subst appell mask ub ent
"<upon>"
	"upon" ukjent
"<the>"
	"the" ukjent
"<door;|>"
	"door;|" ukjent
```

After removing the empty lines (repeated linebreaks), the result is correct:

```
"<«>"
	"$«" <anf>
"<…>"
	"…" subst prop
"<fräulein>"
	"Fräulein" subst prop <*>
"<von>"
	"von" prep
	"von" subst appell fem ub ent
	"von" subst appell mask ub ent
	"vone" verb imp
"<kulp>"
	"Kulp" subst prop <*>
"<may>"
	"may" ukjent
"<turn>"
	"turn" subst appell mask ubøy
	"turne" verb imp
"<,>"
	"$," <komma>
	"$," clb <komma>
"<her>"
	"her" adv
	"her" prep
"<hand>"
	"hand" subst appell fem ub ent
	"hand" subst appell mask ub ent
"<upon>"
	"upon" ukjent
"<the>"
	"the" ukjent
"<door>"
	"door" subst appell fem ub ent samset-analyse <+or>
	"door" subst appell mask ub ent samset-analyse <-or> <+or>
"<;>"
	"$;" clb <semi>
```

The result is the same with and without the `-wxml` option.

**Comment by wanthalf** [comment]
Det gjelder også norsk tekst:

```
"Når det gjelder de som er begravd i Ćelarevo, så ønsker ungarerne at de er ungarere, jødene at de er jøder og muslimene at de er mongoler, men ingen ønsker at de skal være kazarer.
Selv om dette er det mest sannsynlige…
Gravplassen er full av knuste leirkar innrisset med menoraer.
```

Da får man `"<sannsynlige…|>"`. Når jet bare tar de siste to linjer, får jeg `"<sannsynlige…>"...` også med `...` knyttet til ordet, men uten `|`.

**Comment by wanthalf** [comment]
More problems:

1. hyphen/dash disappears, but an extra full stop appears at the end of "sentence":

```
$ echo "Gymnastikk … 6.15-6.30 -"|mtag/mtag.py -wxml
<word>Gymnastikk</word>
"<gymnastikk>"
	"gymnastikk" subst appell mask ub ent
<word>…</word>
"<…>"
	"…" symb
<word>6.15</word>
"<6.15>"
	"6.15" subst <klokke>
<word>6.30</word>
"<6.30>"
	"6.30" det kvant
	"6.30" subst <klokke>
<word>-</word>
"<->"
	"$-" <strek>
<word>.</word>
"<.>"
	"$." clb <<< <punkt>
```


```
$ echo "en colaflaske (plast, 1/2-liter)"|mtag/mtag.py -wxml
<word>en</word>
"<en>"
	"en" adv
	"en" det mask ent kvant
	"en" pron ent pers hum
	"ene" verb imp
<word>colaflaske</word>
"<colaflaske>"
	"colaflaske" subst appell fem ub ent samset-leks <+flaske>
	"colaflaske" subst appell mask ub ent samset-leks <+flaske>
<word>(</word>
"<(>"
	"$(" <parentes-beg>
<word>plast</word>
"<plast>"
	"plast" subst appell mask ub ent
<word>,</word>
"<,>"
	"$," <komma>
	"$," clb <komma>
<word>1/2</word>
"<1/2>"
	"1/2" subst <dato>
<word>liter</word>
"<liter>"
	"lit" subst appell fem ub fl
	"lit" subst appell mask ub fl
	"lite" verb pres
	"liter" subst appell mask ub ent
	"liter" subst appell mask ub fl
<word>)</word>
"<)>"
	"$)" <parentes-slutt>
<word>.</word>
"<.>"
	"$." clb <<< <punkt>
```

```
$ echo "19.30-sending"|mtag/mtag.py -wxml
<word>19.30</word>
"<19.30>"
	"19.30" subst <klokke>
<word>sending</word>
"<sending>"
	"sending" subst appell fem ub ent
	"sending" subst appell mask ub ent
<word>.</word>
"<.>"
	"$." clb <<< <punkt>
```

2. no results at all (in this way several sentences may completely disappear at the end of a text file):

```
$ mtag/mtag.py -wxml
1 gammelt persisk teppe ca kr 700,-
1 nytt teppe ca kr 500,-
$
```

This seems to be a problem of particular combination of punctuation marks and whitespace at the end of the input.

3.  dash/hyphen changed to number ("700,-" changes into "700,1"):

(The last example with the problematic final punctuation removed.)

```
$ mtag/mtag.py -wxml
1 gammelt persisk teppe ca kr 700,-
1 nytt teppe ca kr 500
<word>1</word>
"<1>"
	"1" det ent kvant
<word>gammelt</word>
"<gammelt>"
	"gammel" adj nøyt ub ent pos
<word>persisk</word>
"<persisk>"
	"persisk" adj nøyt ub ent pos
	"persisk" adj ub m/f ent pos
	"persisk" subst appell mask ub ent
	"persisk" subst appell nøyt ubøy
<word>teppe</word>
"<teppe>"
	"teppe" subst appell nøyt ub ent
	"teppe" verb inf
<word>ca</word>
"<ca>"
	"ca" adv
	"ca." adv fork @adv>
<word>kr</word>
"<kr>"
	"kr" subst fork
<word>700,1</word>
"<700,1>"
	"700,1" det fl kvant
<word>nytt</word>
"<nytt>"
	"ny" adj nøyt ub ent pos
	"nyte" adj nøyt ub ent <perf-part>
	"nyte" adj ub m/f ent <perf-part>
	"nyte" verb perf-part
	"nytt" subst appell nøyt ubøy
	"nytte" verb imp
<word>teppe</word>
"<teppe>"
	"teppe" subst appell nøyt ub ent
	"teppe" verb inf
<word>ca</word>
"<ca>"
	"ca" adv
	"ca." adv fork @adv>
<word>kr</word>
"<kr>"
	"kr" subst fork
<word>500</word>
"<500>"
	"500" det fl kvant
<word>.</word>
"<.>"
	"$." clb <<< <punkt>
```

4. an extra full stop appears after abbreviations (which may be an intention, but undesired for us, and I was told it is not consequent either!)

```
$ echo "Mester Eckehart, Sigmund Freud og Karl Marx m.fl."|mtag/mtag.py -wxml
<word>Mester</word>
"<mester>"
	"mester" subst appell mask ub ent
<word>Eckehart</word>
"<eckehart>"
	"Eckehart" subst prop <*>
<word>,</word>
"<,>"
	"$," <komma>
	"$," clb <komma>
<word>Sigmund</word>
"<sigmund>"
	"Sigmund" subst prop mask <*>
<word>Freud</word>
"<freud>"
	"Freud" subst prop <*>
<word>og</word>
"<og>"
	"og" adv
	"og" konj
	"og" konj clb
<word>Karl</word>
"<karl>"
	"Karl" subst prop mask <*>
<word>Marx</word>
"<marx>"
	"Marx" subst prop <*>
<word>m.fl.</word>
"<m.fl.>"
	"mfl." adv fork prep+adj @adv
<word>.</word>
"<.>"
	"$." clb <<< <punkt>
```

**Comment by noklesta** [comment]
> When tagging the following non-Norwegian fragment (usually inside an otherwise Norwegian text, of course, but it also replicates when isolated), we get pipe symbols (not present in the source text) attached to tokens and punctuation symbols (present in the text) attached to them as well:
> 
> ```
> «… Fräulein von Kulp
> 
> 
> may turn, her hand upon the door;
> ```

The pipe symbols mark the end of detected headlines, defined as "sentences" with no more than 8 words and no sentence final punctuation, but followed by a blank line. I have now added a check that the text contains at least one following non-blank line, and that it starts with a capitalized word, and then you get the desired result for your example (with another bugfix giving the correct analysis for the ellipsis):

```
"<«>"
	"$«" <anf>
"<…>"
	"$..." clb <ellipse>
"<fräulein>"
	"Fräulein" subst prop <*>
"<von>"
	"von" prep
	"von" subst appell fem ub ent
	"von" subst appell mask ub ent
	"vone" verb imp
"<kulp>"
	"Kulp" subst prop <*>
"<may>"
	"may" ukjent
"<turn>"
	"turn" subst appell mask ubøy
	"turne" verb imp
"<,>"
	"$," <komma>
	"$," clb <komma>
"<her>"
	"her" adv
	"her" prep
"<hand>"
	"hand" subst appell fem ub ent
	"hand" subst appell mask ub ent
"<upon>"
	"upon" ukjent
"<the>"
	"the" ukjent
"<door>"
	"door" subst appell fem ub ent samset-analyse <+or>
	"door" subst appell mask ub ent samset-analyse <-or> <+or>
"<;>"
	"$;" clb <semi> <<<
```

Additionally, if want to skip the detection of headlines altogether, you can now provide the `-no-headlines` flag.

**Comment by noklesta** [comment]
> More problems:
> 
> 1. hyphen/dash disappears, but an extra full stop appears at the end of "sentence":
> 
> ```
> $ echo "Gymnastikk … 6.15-6.30 -"|mtag/mtag.py -wxml
> ```
> 
> ```
> $ echo "en colaflaske (plast, 1/2-liter)"|mtag/mtag.py -wxml
> ```
> 
> ```
> $ echo "19.30-sending"|mtag/mtag.py -wxml
> ```

The problem with the disappearing hyphen is fixed now. The full stop is appended because the rules of the Constraint Grammar component of The Oslo Bergen Tagger (which is the main target of the mtag output) expects sentences to be terminated. However, you can now apply the `-no-add-stop` if you want to prevent this from happening.

**Comment by noklesta** [comment]
> 2. no results at all (in this way several sentences may completely disappear at the end of a text file):

Your example works now:
```
$ python3 mtag.py -wxml -no-add-stop
1 gammelt persisk teppe ca kr 700,-
1 nytt teppe ca kr 500,-
<word>1</word>
"<1>"
	"1" det ent kvant
<word>gammelt</word>
"<gammelt>"
	"gammel" adj nøyt ub ent pos
<word>persisk</word>
"<persisk>"
	"persisk" adj nøyt ub ent pos
	"persisk" adj ub m/f ent pos
	"persisk" subst appell mask ub ent
	"persisk" subst appell nøyt ubøy
<word>teppe</word>
"<teppe>"
	"teppe" subst appell nøyt ub ent
	"teppe" verb inf
<word>ca</word>
"<ca>"
	"ca" adv
	"ca." adv fork @adv>
<word>kr</word>
"<kr>"
	"kr" subst fork
<word>700,-</word>
"<700,->"
	"700,-" det <beløp>
<word>1</word>
"<1>"
	"1" det ent kvant
<word>nytt</word>
"<nytt>"
	"ny" adj nøyt ub ent pos
	"nyte" adj nøyt ub ent <perf-part>
	"nyte" adj ub m/f ent <perf-part>
	"nyte" verb perf-part
	"nytt" subst appell nøyt ubøy
	"nytte" verb imp
<word>teppe</word>
"<teppe>"
	"teppe" subst appell nøyt ub ent
	"teppe" verb inf
<word>ca</word>
"<ca>"
	"ca" adv
	"ca." adv fork @adv>
<word>kr</word>
"<kr>"
	"kr" subst fork
<word>500,-</word>
"<500,->"
	"500,-" det <beløp>
```

**Comment by noklesta** [comment]
> 3. dash/hyphen changed to number ("700,-" changes into "700,1"):

This was not actually the hyphen being changed to a number, it was the tagger interpreting the hyphen as a mark that a word was split between two lines. Hence, it took the "700," from the first line and the "1" from the following line and concatenated them into what it believed was a word. 

I have now added the constraint that the character preceding the hyphen must be a letter or a digit (e.g. "spise-bord" or "10-talls"), so now it works correctly, as the previous output shows.

**Comment by noklesta** [comment]
> 4. an extra full stop appears after abbreviations (which may be an intention, but undesired for us, and I was told it is not consequent either!)

You can now provide the `-no-add-stop` flag to prevent this from happening. In that case, the final dot is split off from the abbreviation and tagged as the full stop instead of an additional full stop being added after the abbreviation dot:

```
$ echo "Mester Eckehart, Sigmund Freud og Karl Marx m.fl."| python3 mtag.py -wxml -no-add-stop
<word>Mester</word>
"<mester>"
	"mester" subst appell mask ub ent
<word>Eckehart</word>
"<eckehart>"
	"Eckehart" subst prop <*>
<word>,</word>
"<,>"
	"$," <komma>
	"$," clb <komma>
<word>Sigmund</word>
"<sigmund>"
	"Sigmund" subst prop mask <*>
<word>Freud</word>
"<freud>"
	"Freud" subst prop <*>
<word>og</word>
"<og>"
	"og" adv
	"og" konj
	"og" konj clb
<word>Karl</word>
"<karl>"
	"Karl" subst prop mask <*>
<word>Marx</word>
"<marx>"
	"Marx" subst prop <*>
<word>m.fl</word>
"<m.fl>"
	"mfl." adv fork prep+adj @adv
<word>.</word>
"<.>"
	"$." clb <<< <punkt>
```

**Comment by wanthalf** [comment]
Thanks, that is great! As for the question of terminating sentences: we have been lately discussing this again as well. I am not sure about the final decision, but my opinion is that sentences do not necessarily need to be terminated by a full stop. Many sentences end with another punctuation (question mark, exclamation mark, ellipsis, dash, etc.) or nothing at all (e.g. the headlines). So, in the case of abbreviations, I believe the last dot can still be considered part of the token and the sentence may remain without any additional termination symbol as well. If the parser needs a termination token, I think there is a simple solution - an "empty" token:

```
<word></word>
"<.>"
	"$." clb <<< <punkt>
```

But that is just my personal theoretical preference. I guess it does not really matter which solution is applied as long as the users are well informed about the solution chosen.

**Comment by noklesta** [comment]
I totally agree that other solutions might be valid as well - now it just so happens that when no additional full stop is added (i.e., when the -no-add-stop flag is applied), the tagger interprets the final dot as a sentence terminator and tags it that way, leaving the rest of the abbreviation as a separate token. 

Since the final dot is kind of filling two roles simultaneously (as part of the abbreviation and as end-of-sentence marker), I agree that both solutions would be acceptable, but since this solution follows naturally while the one you suggest would require additional programming, I think I am going to leave it like this at the moment.

And of course, as you mention, there are a range of other characters that may mark the end of a sentence - in addition to full stop, question marks, colons, exclamation marks and ellipses are considered end-of-sentence markers by the tagger (and marked with '<<<') if they are followed by a capitalized word.

**Comment by noklesta** [comment]
@wanthalf is it OK to close this issue now?

**Comment by wanthalf** [comment]
Whatever is best for you. We have not tested it yet. We may come with more feedback later and either add it here or open a new issue. What is better?

**Comment by noklesta** [comment]
Ok, I'll close the issue, and if there are problems directly related to the examples you have given here, you could just reopen it. If you discover unrelated problems I think a new issue would be better.
