### ISSUE TITLE
OverflowError in mtag.py

### ISSUE THREAD

**Issue by vit-suchomel** [textlab/mtag#8]
```
wget https://github.com/textlab/mtag/archive/refs/heads/master.zip
unzip master.zip
echo test | mtag-master/mtag.py

Traceback (most recent call last):
  File "./mtag-master/mtag.py", line 330, in <module>
    from fullform_bm import fullformHash
OverflowError: line number table is too long
```
Python 3.10.11

**Comment by noklesta** [comment]
This seems to be a problem with Python 3.10. I am able to reproduce using Python 3.10.13 (from DockerHub), but both 3.9.18 and 3.11.6 work fine. Do you have the possibility of upgrading or downgrading Python (potentially using Docker)?

**Comment by vit-suchomel** [comment]
Thank you, Anders, I tried using Python 3.12.0 an it works now!

**Comment by noklesta** [comment]
That's great!
